baseURL: https://alldevops.netlify.app/
languageCode: en-us
params:
  AuthorName: Chris Cheng
  SidebarRecentLimit: 15
  Subtitle: Living coding
permalinks:
  posts: /:year/:month/:title/
title: All About Dev & Ops
theme: clarity